In [1]:
import os
import json

import pandas as pd

# Transients & sky locations

In [2]:
# Event sky locations
locs = {
    "PS1-10jh": {
        "ra": 242.368075,
        "dec": 53.673492,
        "trans_type": "TDE",
        "pub_date": "2012",
    },
    "PS1-11af": {
        "ra": 149.36175,
        "dec": 3.23361,
        "trans_type": "TDE",
        "pub_date": "2013",
    },
    "D3-13": {
        "ra": 214.8741,
        "dec": 52.8684,
        "trans_type": "TDE",
        "pub_date": "2006",
    },
    "D1-9": {
        "ra": 36.3207,
        "dec": 4.5497,
        "trans_type": "TDE",
        "pub_date": "2008",
    },
    "D23H-1": {
        "ra": 352.99804167,
        "dec": 0.28738056,
        "trans_type": "TDE",
        "pub_date": "2009",
    },
    "PS1-13arp": {
        "ra": 184.604295,
        "dec": 46.616852,
        "trans_type": "SN2p",
        "pub_date": "2008",
    },
    "SN-2010aq": {
        "ra": 150.5405875,
        "dec": 1.23359444,
        "trans_type": "SN2p",
        "pub_date": "2010",
    },
    "test": {
        "ra": 176.919525856024,
        "dec": 0.255696872807351,
        "trans_type": "test",
        "pub_date": "0",
    },
}

df_locs = pd.DataFrame.from_dict(locs)
df_locs

,PS1-10jh,PS1-11af,D3-13,D1-9,D23H-1,PS1-13arp,SN-2010aq,test
ra,242.368075,149.36175,214.8741,36.3207,352.998042,184.604295,150.540587,176.919526
dec,53.673492,3.23361,52.8684,4.5497,0.287381,46.616852,1.233594,0.255697
trans_type,TDE,TDE,TDE,TDE,TDE,SN2p,SN2p,test
pub_date,2012,2013,2006,2008,2009,2008,2010,0

In [3]:
# Save transient list to disc
save_locs = False
if save_locs:
    # as JSON
    with open("transients.json", "w") as f:
        json.dump(locs, f, indent=4)
    # as CSV
    df_locs.to_csv("transients.csv")